# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9 on 2016-01-19 18:29
=======
# Generated by Django 1.9 on 2016-01-18 19:45
>>>>>>> c338d0d926c70266ee8ca0a8dd57d76a320906bb
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileserverBasket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mobileServer_basket',
            },
        ),
        migrations.CreateModel(
            name='MobileserverCart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('checked_out', models.BooleanField()),
            ],
            options={
                'db_table': 'mobileServer_cart',
            },
        ),
        migrations.CreateModel(
            name='MobileserverCartitem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'mobileServer_cartitem',
            },
        ),
        migrations.CreateModel(
            name='MobileserverOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('totalprice', models.FloatField(db_column=b'totalPrice')),
=======
                ('totalprice', models.FloatField(db_column='totalPrice')),
>>>>>>> c338d0d926c70266ee8ca0a8dd57d76a320906bb
            ],
            options={
                'db_table': 'mobileServer_order',
            },
        ),
        migrations.CreateModel(
            name='MobileserverOrderProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mobileServer_order_product',
            },
        ),
        migrations.CreateModel(
            name='MobileserverProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('category', models.IntegerField()),
                ('img', models.TextField()),
            ],
            options={
                'db_table': 'mobileServer_product',
            },
        ),
        migrations.CreateModel(
            name='MobileserverShop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'db_table': 'mobileServer_shop',
            },
        ),
        migrations.CreateModel(
            name='MobileserverShopinventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.BooleanField()),
            ],
            options={
                'db_table': 'mobileServer_shopinventory',
            },
        ),
        migrations.CreateModel(
            name='MobileserverShopinventoryProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shopinventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverShopinventory')),
            ],
            options={
                'db_table': 'mobileServer_shopinventory_product',
            },
        ),
        migrations.CreateModel(
            name='MobileserverShopproductinventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverProduct')),
            ],
            options={
                'db_table': 'mobileServer_shopproductinventory',
            },
        ),
        migrations.AddField(
            model_name='mobileservershopinventoryproduct',
            name='shopproductinventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverShopproductinventory'),
        ),
    ]
