# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileServer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileservershopinventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='mobileservershopinventory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverShop', unique=True),
        ),
        migrations.AddField(
            model_name='mobileserverorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverOrder'),
        ),
        migrations.AddField(
            model_name='mobileserverorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverProduct'),
        ),
        migrations.AddField(
            model_name='mobileserverorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobileserverorder',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverShop', unique=True),
        ),
        migrations.AddField(
            model_name='mobileservercartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverCart'),
        ),
        migrations.AddField(
            model_name='mobileservercartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverShopproductinventory'),
        ),
        migrations.AddField(
            model_name='mobileservercart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobileserverbasket',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mobileServer.MobileserverCart'),
        ),
        migrations.AddField(
            model_name='mobileserverbasket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mobileservershopinventoryproduct',
            unique_together=set([('shopinventory', 'shopproductinventory')]),
        ),
    ]
